nthroot: nthroot.cpp
	g++ -O3 -std=c++11 nthroot.cpp -o nthroot

prime_heap: prime_heap.cpp
	g++ -O3 -std=c++11 prime_heap.cpp -o prime_heap

all: nthroot prime_heap

clean: 
	rm *.o nthroot prime_heap a.out
